### ISSUE TITLE
Problem when connect pluto

### ISSUE THREAD

**Issue by Koreko209** [krakenrf/krakensdr_doa#120]
Hi i want to work with pluto sdr at the same time when i use doa of krakensdr but when i connect pluto on raspberry the result of the doa is change in random result and when i stop the doa and restart it the calibration and the delay synch losses and the doa stop.
Why this problem appear?
Thanks

**Comment by krakenrf** [comment]
Hi, unfortunately this won't be possible with a Raspberry Pi. On a Pi the USB bandwidth is quite limited and the KrakenSDR relies on the USB bandwidth being uncontested in order to keep sample alignment. Any other device with high USB data usage is going to cause the KrakenSDR to stop working correctly.
