### ISSUE TITLE
VFO settings changes in the settings.json file are not reflected in the UI

### ISSUE THREAD

**Issue by dubrsl** [krakenrf/krakensdr_doa#124]
VFO settings changes in the settings.json file are not reflected in the UI.

According to the latest changes, all changes in the UI are automatically saved in settings.json. It is expected that changing settings.json directly will be displayed in the UI too.
But this does not work for fields in the VFO-0 block.
Refreshing the page helps.

STR: 
1. Edit "vfo_freq_0" in settings.json
2. Check the fild VFO-0 Frequency [MHz]: in UI

**Comment by rtlsdrblog** [comment]
I think it's just that you need to remember to set "ext_upd_flag" to true in the JSON if you want to push a GUI update. So any external software writing changes to settings.json needs to set this true. The Kraken software will set it back to False after the update it done.

I just tested and VFO updates are working as long as the flag is set to true.

This is to stop a feedback loop when the krakenSDRs own web GUI is changed by the user. Otherwise it ends up in an infinite loop checking the file for changes and saving constantly over and over.
