### ISSUE TITLE
Unsupported Compression Method: 14

### ISSUE THREAD

**Issue by cisrgistics** [krakenrf/krakensdr_doa#46]
About to do a road trip. Had some ULA signals lined up. Noticed the update. Downloaded. BalenaEtcher said the v1.4 zip file was unsupported. Realizing my age and level of stupidity I thought maybe I touched something wrong. Tried directly from the link to the file on github. No dice. BalenaEtcher cried again. I can't update. Using a Win10 machine with MS Edge browser....Also, why is it the other version zip files have disappeared? CYA decisions or we're not allowed to blend code between versions?

**Comment by n8rdf** [comment]
My Balena worked fine with v1.4 image.

**Comment by cisrgistics** [comment]
Since your zip didnt have any issues, how about you upload your copy to my folder? https://1drv.ms/u/s!AoICwvibJ8iOhMNYOUW31ZKw9_vJGQ?e=MTJvza
![Capture](https://user-images.githubusercontent.com/115653054/200181480-cbeec377-6c91-49a3-a556-4681a91c26f5.JPG)

**Comment by cisrgistics** [comment]
and this
![Capture 2](https://user-images.githubusercontent.com/115653054/200181646-a9402455-9a02-4254-9de4-9bd8bd741a59.JPG)

**Comment by cisrgistics** [comment]
and this effort
![Capture 3](https://user-images.githubusercontent.com/115653054/200182040-60da4c42-3b8a-429f-821e-2bf391eac9f9.JPG)

**Comment by cisrgistics** [comment]
Which has the same result:
![Capture 4](https://user-images.githubusercontent.com/115653054/200182212-41b340ae-9868-4515-90a4-9f7c4efa2821.JPG)

**Comment by n8rdf** [comment]
Did you try downloading the image zip first, then extracting from the local copy? That's how I did it.

**Comment by krakenrf** [comment]
Interesting looks like whatever compression library Etcher is using doesn't support LZMA compression. We switched to that for greater compression efficiency because otherwise it was going over the 2GB limit for GitHub. Will look at changing the compression method, or uploading elsewhere.

For now please just unzip the file first with 7zip.

We had to remove the older images due to a very unfortunate legal regulation requirement for passive radar which we just became aware of. We need to wait on the lawyers to sort that out before we can say or do anything else.

**Comment by krakenrf** [comment]
Ok updated to .xz LMZA2 compression which etcher seems to support. Should be OK now.
