### ISSUE TITLE
Image 1.4 DOA issue: Spectrum Autoscale stuck on? 

### ISSUE THREAD

**Issue by n8rdf** [krakenrf/krakensdr_doa#51]
When attempting to use the [zoom],  [+] or [-] control keys on the DOA Spectum screen, the screen changes briefly when the control is selected, but then immediately reverts to full (auto?) scale.  Pressing the [autoscale] control (toggle?) does not change the symptoms.  Observed in firefox on a windows PC and Samsung Tab A8 android tablet.

**Comment by krakenrf** [comment]
Unfortunately the graphing library we use doesn't have very good support for live updates, as it has to essentially redraw and reset the entire graph each time instead of just updating the data. There are ways to update just the data, but then we lose the ability to plot the text on the graph. So it's been a trade off.
