### ISSUE TITLE
Spectrum display controls inoperable

### ISSUE THREAD

**Issue by BrunoKlu** [krakenrf/krakensdr_doa#57]
Impossible to control, zoom, spectrum slide,from the web interface. Video attached. Tried on windows with Firefox also on Ipad with Safari, chrome and firefox.

https://user-images.githubusercontent.com/73705824/211155833-ebbab4f9-b45a-4e30-b198-4639986ad3b3.MOV

**Comment by krakenrf** [comment]
Yes this is expected behavior. Unfortunately this is a limitation of the graphing library used and we've not found any other suitable replacements libraries. The entire spectrum graph has to refresh on each tick, so any zooms or changes will be reset.

There is no spectrum slide to change frequency implemented as that would be incompatible with the KrakenSDRs need to calibrate on each frequency retune.
