### ISSUE TITLE
Issues when disabling WIFI

### ISSUE THREAD

**Issue by Tysonpower** [krakenrf/krakensdr_doa#61]
There where reports that the DOA Software stops sending Data to the Remote Server (map.krakenrf.com) if wifi is disabled despite it being connected to the Internet via Ethernet.

The Kraken Software tries to connect as a client, if this doesen't work it will create an AP.
My guess is that this fails when wifi is disabled and causes an issue in the Software Stack startup.

One User wrote:

> It's a Stationary station. Everything works on Raspberry PI4 V1.43, but I
would like to disable the Wi-Fi interface. When you turn off the Wi-Fi
interface (command: dtoverlay=disable-wifi
dtoverlay=disable-bt (in config.txt)), the device disappears from the
cloud, although Internet access remains.  In the cloud, the device is
displayed as inactive.

@krakenrf Carl please have a look if this is the case

**Comment by krakenrf** [comment]
I tried to replicate this problem but was unsuccessful. Perhaps it was because when testing I initially disable the Autohotspot script which could be causing a system error is WiFi is forcefully disabled in boot/config.txt.

I added a bit on the Wiki about how to disable the Autohotspot script here https://github.com/krakenrf/krakensdr_docs/wiki/12.-Appendix#disabling-the-wifi-hotspot
